[package]
name = "spiderlightning"
version = "0.1.0"
edition = "2021"
authors = ["DeisLabs Engineering Team"]

[lib]
doctest = false

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
short-crypt = "1"
rand = "0.8"
toml = "0.5"
tempdir = "0.3"

[dev-dependencies]
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1.20", features = ["full"] }

[target.'cfg(unix)'.dev-dependencies]
signal-child = "1"

[workspace]
members = [
    "slight",
    "crates/kv",
    "crates/mq",
    "crates/lockd",
    "crates/http",
    "crates/http-api",
    "crates/http-handler-macro",
    "crates/pubsub",
    "crates/runtime",
    "crates/events",
    "crates/events-api",
    "crates/runtime-configs",
    "crates/common",
]
