[package]
name = "spiderlightning"
version = "0.1.0"
edition = "2021"
authors = ["DeisLabs Engineering Team"]

[lib]
doctest = false

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
short-crypt = "1"
rand = "0.8"
toml = "0.5"
tempdir = "0.3"

[dev-dependencies]
hyper = { version = "0.14", features = ["full"] }

[workspace]
members = [
    "slight",
    "crates/kv",
    "crates/mq-filesystem",
    "crates/mq-azure-servicebus",
    "crates/http-api",
    "crates/http-handler-macro",
    "crates/lockd-etcd",
    "crates/pubsub-confluent-kafka",
    "crates/runtime",
    "crates/events",
    "crates/events-api",
    "crates/runtime-configs",
    "examples/kv-demo",
    "examples/mq-sender-demo",
    "examples/mq-receiver-demo",
    "examples/multi_capability-demo",
    "examples/lockd-demo",
    "examples/pubsub-consumer-demo",
    "examples/pubsub-producer-demo",
    "examples/watch-demo",
    "examples/configs-demo",
    "examples/http-demo",
]
