specversion = "0.2"

[[capability]]
resource = "http"
name = "my-rest-api"
    # This capability does not require any configs

[[capability]]
resource = "mq.filesystem"
name = "slight-restaurant"
    # This capability does not require any configs